In [1]:
import torch
import numpy as np
import os

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cpu'

In [3]:
basic_tensor=torch.tensor([[1,2,3],[11,22,33]])
basic_tensor

tensor([[ 1,  2,  3],
        [11, 22, 33]])

In [4]:
basic_tensor.dtype

torch.int64

In [5]:
basic_tensor.shape

torch.Size([2, 3])

In [6]:
basic_tensor.requires_grad

False

In [7]:
tensor = torch.tensor([[1,2,3],[11,22,33]],
                     dtype=torch.float,
                     device=device,
                     requires_grad=True)

tensor

tensor([[ 1.,  2.,  3.],
        [11., 22., 33.]], requires_grad=True)

In [9]:

tensor.dtype

torch.float32

In [8]:
tensor.device

device(type='cpu')

In [10]:
tensor.requires_grad

True

Other commonly used tensors

In [13]:
x=torch.empty(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
x=torch.zeros(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
x=torch.rand(size=(3,3))
x

tensor([[0.8946, 0.7638, 0.9832],
        [0.4573, 0.3927, 0.4482],
        [0.9512, 0.9582, 0.2115]])

In [15]:
x=torch.ones(size=(3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
x=torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
x=torch.arange(start=0, end=8, step=2)
x

tensor([0, 2, 4, 6])

In [24]:
x=torch.linspace(start=0, end=7, steps=10)
x

tensor([0.0000, 0.7778, 1.5556, 2.3333, 3.1111, 3.8889, 4.6667, 5.4444, 6.2222,
        7.0000])

In [26]:
x=torch.rand(size=(3,3)).normal_(mean=0, std=1)
x

tensor([[-1.5999,  0.3630, -0.9451],
        [-1.7218,  0.1964,  0.9224],
        [-0.4810, -0.0528, -0.8338]])

In [28]:
x=torch.rand(size=(3,3)).uniform_(8,10)
x

tensor([[8.0024, 9.4004, 8.2235],
        [8.7691, 9.9125, 8.0917],
        [9.9483, 9.1624, 9.0244]])

In [29]:
x = torch.diag(torch.ones(10))
x

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
x.shape

torch.Size([10, 10])

In [31]:
x = torch.diag(5*torch.ones(10))
x

tensor([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

Conversions

In [32]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [33]:
x.bool()

tensor([False,  True,  True,  True])

In [34]:
x.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [35]:
x.float()#float32

tensor([0., 1., 2., 3.])

In [36]:
x.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [37]:
x.long()

tensor([0, 1, 2, 3])

In [38]:
x.half()#float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [39]:
x.double()#float64

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [40]:
np_array = np.array([[1,2,3], [1,2,3]])

np_array

array([[1, 2, 3],
       [1, 2, 3]])

In [41]:
tensor=torch.from_numpy(np_array)
tensor 

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)

In [42]:
tensor.numpy()

array([[1, 2, 3],
       [1, 2, 3]])