In [1]:
import numpy as np
import torch
import os

In [2]:
x = torch.arange(start=10, end=20, step=4)
y = torch.arange(start=5, end=15, step=4)

x.shape, y.shape

(torch.Size([3]), torch.Size([3]))

In [3]:
x

tensor([10, 14, 18])

In [4]:
y

tensor([ 5,  9, 13])

In [5]:
x+y

tensor([15, 23, 31])

In [6]:
x-y

tensor([5, 5, 5])

In [7]:
x*y#element wise multiplication

tensor([ 50, 126, 234])

In [8]:
x/y #element wise division

tensor([2.0000, 1.5556, 1.3846])

In [9]:
z=torch.ones(3)
z

tensor([1., 1., 1.])

In [10]:
z=z+x
z

tensor([11., 15., 19.])

In [11]:
z.add_(x)
z#inplace addition

tensor([21., 29., 37.])

In [13]:
x.pow(2)

tensor([100, 196, 324])

In [14]:
x>0

tensor([True, True, True])

In [24]:
torch.dot(x, y)

tensor(410)

In [15]:
# Matrix multpltplication

A = torch.rand(size=(3,5))
B = torch.rand(size=(5,4))

A @ B 

tensor([[1.1904, 1.9249, 1.8291, 1.2449],
        [0.5076, 0.8828, 0.5493, 0.6339],
        [0.4911, 0.6913, 0.7842, 0.2886]])

In [16]:
A.matmul(B)

tensor([[1.1904, 1.9249, 1.8291, 1.2449],
        [0.5076, 0.8828, 0.5493, 0.6339],
        [0.4911, 0.6913, 0.7842, 0.2886]])

In [17]:
X = torch.rand((3,3))
X.matrix_exp()

tensor([[3.3708, 2.1202, 1.2823],
        [2.5868, 3.0709, 1.9745],
        [1.2495, 1.7852, 2.8822]])

In [18]:
X.matrix_power(2)

tensor([[1.5323, 1.2206, 0.9411],
        [1.4633, 1.5377, 1.1542],
        [0.9597, 1.0158, 1.1448]])

In [19]:
#broadcasting

A

tensor([[0.3682, 0.8247, 0.1942, 0.8253, 0.6864],
        [0.1515, 0.0583, 0.3357, 0.2294, 0.4613],
        [0.0701, 0.6168, 0.0182, 0.2101, 0.0267]])

In [20]:
A+1

tensor([[1.3682, 1.8247, 1.1942, 1.8253, 1.6864],
        [1.1515, 1.0583, 1.3357, 1.2294, 1.4613],
        [1.0701, 1.6168, 1.0182, 1.2101, 1.0267]])

In [21]:
A*5

tensor([[1.8409, 4.1234, 0.9711, 4.1267, 3.4320],
        [0.7575, 0.2916, 1.6785, 1.1470, 2.3067],
        [0.3506, 3.0840, 0.0910, 1.0503, 0.1335]])

In [22]:
A-5

tensor([[-4.6318, -4.1753, -4.8058, -4.1747, -4.3136],
        [-4.8485, -4.9417, -4.6643, -4.7706, -4.5387],
        [-4.9299, -4.3832, -4.9818, -4.7899, -4.9733]])

In [23]:
A.shape

torch.Size([3, 5])

In [25]:
C = torch.ones((1,5))
C

tensor([[1., 1., 1., 1., 1.]])

In [26]:
A-C

tensor([[-0.6318, -0.1753, -0.8058, -0.1747, -0.3136],
        [-0.8485, -0.9417, -0.6643, -0.7706, -0.5387],
        [-0.9299, -0.3832, -0.9818, -0.7899, -0.9733]])

In [27]:
A+C

tensor([[1.3682, 1.8247, 1.1942, 1.8253, 1.6864],
        [1.1515, 1.0583, 1.3357, 1.2294, 1.4613],
        [1.0701, 1.6168, 1.0182, 1.2101, 1.0267]])

In [28]:
D = torch.ones((3, 1))
D

tensor([[1.],
        [1.],
        [1.]])

In [29]:
A- D

tensor([[-0.6318, -0.1753, -0.8058, -0.1747, -0.3136],
        [-0.8485, -0.9417, -0.6643, -0.7706, -0.5387],
        [-0.9299, -0.3832, -0.9818, -0.7899, -0.9733]])

In [30]:
A+D

tensor([[1.3682, 1.8247, 1.1942, 1.8253, 1.6864],
        [1.1515, 1.0583, 1.3357, 1.2294, 1.4613],
        [1.0701, 1.6168, 1.0182, 1.2101, 1.0267]])

In [31]:
torch.sum(D)

tensor(3.)

In [32]:
torch.sum(A)

tensor(5.0770)

In [33]:
torch.max(A)

tensor(0.8253)

In [34]:
torch.min(A)

tensor(0.0182)

In [35]:
torch.min(A,dim=1)# row wise max 

torch.return_types.min(
values=tensor([0.1942, 0.0583, 0.0182]),
indices=tensor([2, 1, 2]))

In [36]:
torch.max(A, dim=0) # col wise max

torch.return_types.max(
values=tensor([0.3682, 0.8247, 0.3357, 0.8253, 0.6864]),
indices=tensor([0, 0, 1, 0, 0]))

In [37]:
torch.abs(-A)

tensor([[0.3682, 0.8247, 0.1942, 0.8253, 0.6864],
        [0.1515, 0.0583, 0.3357, 0.2294, 0.4613],
        [0.0701, 0.6168, 0.0182, 0.2101, 0.0267]])

In [38]:
A

tensor([[0.3682, 0.8247, 0.1942, 0.8253, 0.6864],
        [0.1515, 0.0583, 0.3357, 0.2294, 0.4613],
        [0.0701, 0.6168, 0.0182, 0.2101, 0.0267]])

In [39]:
torch.argmax(A)

tensor(3)

In [40]:
torch.argmax(A, dim=1) # row wise argmax

tensor([3, 4, 1])

In [41]:

torch.argmax(A, dim=0) # col wise argmax

tensor([0, 0, 1, 0, 0])

In [42]:
torch.argmin(A)

tensor(12)

In [43]:
torch.mean(A)

tensor(0.3385)

In [44]:
A

tensor([[0.3682, 0.8247, 0.1942, 0.8253, 0.6864],
        [0.1515, 0.0583, 0.3357, 0.2294, 0.4613],
        [0.0701, 0.6168, 0.0182, 0.2101, 0.0267]])

In [45]:
D = torch.ones(A.shape)
D

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [46]:
torch.eq(A, D)


tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [47]:

torch.eq(D, D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [48]:
torch.sort(A)

torch.return_types.sort(
values=tensor([[0.1942, 0.3682, 0.6864, 0.8247, 0.8253],
        [0.0583, 0.1515, 0.2294, 0.3357, 0.4613],
        [0.0182, 0.0267, 0.0701, 0.2101, 0.6168]]),
indices=tensor([[2, 0, 4, 1, 3],
        [1, 0, 3, 2, 4],
        [2, 4, 0, 3, 1]]))

In [49]:
torch.clamp(A, min=0.5)

tensor([[0.5000, 0.8247, 0.5000, 0.8253, 0.6864],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.6168, 0.5000, 0.5000, 0.5000]])