In [1]:
import numpy as np
import torch
import os

In [2]:
x = torch.rand(size=(3,4))
x

tensor([[0.8187, 0.8602, 0.5961, 0.4385],
        [0.6432, 0.3944, 0.4123, 0.1063],
        [0.0139, 0.1774, 0.4184, 0.9227]])

x[row, cols]

row -> start:stop:step

col -> start:stop:step

In [6]:
x[0,:]

tensor([0.8187, 0.8602, 0.5961, 0.4385])

In [7]:
x[:,0]

tensor([0.8187, 0.6432, 0.0139])

In [11]:
x[0:2,0:4]

tensor([[0.8187, 0.8602, 0.5961, 0.4385],
        [0.6432, 0.3944, 0.4123, 0.1063]])

In [12]:
x[0,0]

tensor(0.8187)

In [14]:
x[0,0]=11

In [15]:
x = torch.rand(size=(3,4))
y = torch.rand(size=(3,4))

Concatination

In [16]:
torch.cat((x, y), dim=1)

tensor([[0.5482, 0.5042, 0.5626, 0.0415, 0.3887, 0.3317, 0.0151, 0.4223],
        [0.9129, 0.0233, 0.1488, 0.7407, 0.4347, 0.2629, 0.8923, 0.4291],
        [0.0048, 0.2082, 0.8398, 0.0559, 0.1765, 0.1434, 0.6782, 0.0364]])

In [17]:
torch.cat((x, y), dim=0)

tensor([[0.5482, 0.5042, 0.5626, 0.0415],
        [0.9129, 0.0233, 0.1488, 0.7407],
        [0.0048, 0.2082, 0.8398, 0.0559],
        [0.3887, 0.3317, 0.0151, 0.4223],
        [0.4347, 0.2629, 0.8923, 0.4291],
        [0.1765, 0.1434, 0.6782, 0.0364]])

In [18]:
x.shape

torch.Size([3, 4])

Reshaping

In [19]:
x.reshape(2,6)

tensor([[0.5482, 0.5042, 0.5626, 0.0415, 0.9129, 0.0233],
        [0.1488, 0.7407, 0.0048, 0.2082, 0.8398, 0.0559]])

In [20]:

x.reshape(2,3) # no. of elements should match

RuntimeError: shape '[2, 3]' is invalid for input of size 12

In [21]:
x.reshape(1,12)

tensor([[0.5482, 0.5042, 0.5626, 0.0415, 0.9129, 0.0233, 0.1488, 0.7407, 0.0048,
         0.2082, 0.8398, 0.0559]])

In [22]:
x.reshape(12,1)

tensor([[0.5482],
        [0.5042],
        [0.5626],
        [0.0415],
        [0.9129],
        [0.0233],
        [0.1488],
        [0.7407],
        [0.0048],
        [0.2082],
        [0.8398],
        [0.0559]])

In [23]:
x.shape

torch.Size([3, 4])

In [24]:

x.view(-1) # Flattening

tensor([0.5482, 0.5042, 0.5626, 0.0415, 0.9129, 0.0233, 0.1488, 0.7407, 0.0048,
        0.2082, 0.8398, 0.0559])

In [25]:

x.view(-1).shape # flattening a tensor

torch.Size([12])

In [26]:
# batch flattening ops
batch = 16

torch.rand((batch, 2,5)).view((batch, -1))

tensor([[0.6753, 0.7641, 0.2727, 0.7447, 0.6420, 0.3586, 0.5142, 0.7599, 0.8625,
         0.5427],
        [0.1613, 0.8284, 0.6049, 0.7337, 0.7649, 0.0401, 0.3695, 0.3453, 0.0837,
         0.3592],
        [0.2476, 0.8871, 0.7261, 0.2464, 0.7061, 0.2310, 0.9934, 0.8402, 0.0551,
         0.8527],
        [0.1583, 0.0856, 0.0820, 0.2453, 0.1249, 0.0757, 0.3914, 0.5854, 0.5021,
         0.3247],
        [0.5501, 0.1637, 0.5758, 0.9903, 0.0397, 0.2714, 0.7924, 0.2292, 0.9633,
         0.1651],
        [0.8209, 0.6783, 0.0718, 0.5039, 0.4829, 0.9246, 0.1145, 0.6250, 0.9392,
         0.2322],
        [0.7335, 0.7736, 0.1912, 0.0260, 0.4966, 0.8842, 0.8166, 0.8114, 0.3983,
         0.7577],
        [0.1796, 0.1671, 0.3103, 0.4982, 0.4181, 0.3645, 0.7068, 0.5101, 0.1736,
         0.4804],
        [0.5649, 0.5858, 0.5574, 0.3131, 0.2298, 0.2293, 0.6189, 0.7461, 0.5849,
         0.2744],
        [0.3509, 0.9134, 0.4071, 0.4097, 0.2577, 0.8408, 0.8537, 0.6068, 0.0995,
         0.6237],
        [0